:page-toclevels: -1


= Endpoints

This page contains a list of the endpoints that the Query API provides, plus pointers to other HTTP endpoints available on a Neo4j server.

[cols="2m, 3"]
|===
|Endpoint location |Description

|/
|To obtain a list of available endpoints on your installation and some basic server information.

|/db/<databaseName>/query/v2
|To submit queries. +
For more information, see xref:query.adoc[].

|/db/<databaseName>/query/v2/tx
|To open an explicit transaction. +
For more information, see xref:transactions.adoc[].

|/db/<databaseName>/query/v2/tx/<transactionID>
|To submit queries to an open transaction with ID `<transactionID>`. +
A `DELETE` request results in a rollback. +
For more information, see xref:transactions.adoc#rollback[Run transactions -> Rollback a transaction].

|/db/<databaseName>/query/v2/tx/<transactionID>/commit
|To commit an open transaction with ID `<transactionID>`. +
For more information, see xref:transactions.adoc#commit[Run transactions -> Commit a transaction].

|===


[[discovery-api]]
== Discovery API

To obtain a list of available endpoints on your installation, together with some basic server information, send an un-authenticated `GET` request to the server root.

[discrete]
=== Example request

[source, headers]
----
GET http://localhost:7474/
----

[discrete]
=== Example response

[source, JSON]
----
{
    "bolt_routing": "neo4j://localhost:7687",
    "query": "http://localhost:7474/db/{databaseName}/query/v2",
    "dbms/cluster": "http://localhost:7474/dbms/cluster",
    "db/cluster": "http://localhost:7474/db/{databaseName}/cluster",
    "transaction": "http://localhost:7474/db/{databaseName}/tx",
    "bolt_direct": "bolt://localhost:7687",
    "neo4j_version": "2026.03",
    "neo4j_edition": "enterprise",
    "auth_config": {
        "oidc_providers": []
    }
}
----

[NOTE]
Bolt routing is meant to be used with link:{neo4j-docs-base-uri}/create-applications/[client libraries (Drivers)].
