:page-role: beta

= Headers

This page contains a full list of headers you may use to tweak the API behavior, or that the API may return in responses.

== Request headers

[cols="1m, 3"]
|===
|Header |Description

|Accept
|Desired format of the response body. +
Possible values are `application/json` (default) and `application/vnd.neo4j.query`. +
For more information, see xref:result-formats.adoc[].

|Authorization
|Authentication credentials to authorize the request. +
For more information, see xref:authentication-authorization.adoc[].

|Content-Type
|The format of the request body. +
Possible values are `application/json` and `application/vnd.neo4j.query`. +
For more information, see xref:result-formats.adoc[].

|===

== Response headers

[cols="1m, 3"]
|===
|Header |Description

|Content-Type
|The format of the response body (matches the `Accept` request header). +
Possible values are `application/json` and `application/vnd.neo4j.query`. +
For more information, see xref:result-formats.adoc[].

|===
