= Headers

This page contains a full list of headers you may use to tweak the API behavior, or that the API may return in responses.

== Request headers

[cols="1m, 3"]
|===
|Header |Description

|Accept
|Desired format of the response body. +
Possible values are `application/json` (default) and `application/vnd.neo4j.query`. +
For more information, see xref:result-formats.adoc[].

|Authorization
|Authentication credentials to authorize the request. +
For more information, see xref:authentication-authorization.adoc[].

|Content-Type
|The format of the request body. +
Possible values are `application/json` and `application/vnd.neo4j.query`. +
For more information, see xref:result-formats.adoc[].

|neo4j-cluster-affinity
label:aura-only[]
|The cluster member handling the transaction, as received as response header by previous transaction requests.
It must be included with all requests working with a specific transaction.
For more information, see xref:transactions.adoc[].

|===

== Response headers

[cols="1m, 3"]
|===
|Header |Description

|Content-Type
|The format of the response body (matches the `Accept` request header). +
Possible values are `application/json` and `application/vnd.neo4j.query`. +
For more information, see xref:result-formats.adoc[].

|neo4j-cluster-affinity
label:aura-only[]
|The cluster member handling the transaction.
It must be included as a header to all subsequent requests, including commit/rollback requests.
For more information, see xref:transactions.adoc[].

|===
