:description: The Query API allows to execute Cypher statements against a Neo4j server through HTTP requests.
:page-role: new-5.19


= Introduction

[NOTE]
The Query API is enabled by default on all <<Aura>> tiers, but disabled on self-managed instances.
To enable it, add `QUERY_API_ENDPOINTS` to the configuration setting link:https://neo4j.com/docs/operations-manual/current/configuration/configuration-settings/#config_server.http_enabled_modules[`server.http_enabled_modules`].

The Query API allows to execute Cypher statements against a Neo4j server through HTTP requests.

The main use case of the API is for developing client applications in languages for which there is no supported library.
If there exists an official library (driver) for the language you are using, consider using that instead -- see link:{neo4j-docs-base-uri}/create-applications/[Create applications].

**On self-managed instances**, the API uses port 7474 for HTTP and port 7473 for HTTPS by default. Ports can be altered via the configuration settings link:https://neo4j.com/docs/operations-manual/current/configuration/configuration-settings/#config_server.http.listen_address[`server.http.listen_address`] and link:https://neo4j.com/docs/operations-manual/current/configuration/configuration-settings/#config_server.https.listen_address[`server.https.listen_address`]. +
**Aura instances** support only HTTPS through port 443.

This guide assumes that you have:

- A running instance of Neo4j -- If you don't have one, link:https://neo4j.com/docs/operations-manual/current/installation/[install Neo4j locally] or sign up for an link:https://neo4j.com/cloud/platform/aura-graph-database/[Aura cloud instance].
- Some familiarity with <<Cypher>> -- If you are new to it, check out link:https://neo4j.com/docs/getting-started/cypher-intro/[Getting started -> Cypher].

<<<<<<< Updated upstream
**On self-managed instances**, the API uses port 7474 for HTTP and port 7473 for HTTPS by default. Ports can be altered via the configuration settings link:https://neo4j.com/docs/operations-manual/current/configuration/configuration-settings/#config_server.http.listen_address[`server.http.listen_address`] and link:https://neo4j.com/docs/operations-manual/current/configuration/configuration-settings/#config_server.https.listen_address[`server.https.listen_address`]. +
**Aura instances** support only HTTPS through port 443.
=======
<<<<<<< Updated upstream
=======
[TIP]
>>>>>>> Stashed changes
The Query API supports HTTP/2 as well as HTTP/1.1, unless either is explicitly disabled in the server configuration setting link:https://neo4j.com/docs/operations-manual/current/configuration/configuration-settings/#config_server.http_enabled_transports[`server.http_enabled_transports`].
It's up to the client to initiate a connection with the preferred protocol.
>>>>>>> Stashed changes

[TIP]
The Query API supports HTTP/2 as well as HTTP/1.1, unless either is explicitly disabled in the server configuration setting link:https://neo4j.com/docs/operations-manual/current/configuration/configuration-settings/#config_server.http_enabled_transports[`server.http_enabled_transports`].
It's up to the client to initiate a connection with the preferred protocol.


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::{partials}/glossary.adoc[]
endif::[]
