:page-role: new-2025.12

= Stream results

The Query API can stream values as events over HTTP.
This allows clients to process data incrementally as it arrives, improving memory efficiency and enabling applications to handle larger datasets.

You enable streaming by tweaking the `Accept` header:

* For xref:plain-json.adoc[Plain JSON], `application/jsonl`.
* For xref:typed-json.adoc[Typed JSON], add the suffix `+jsonl`. For example, `{typed-json-version}+jsonl`.

[NOTE]
For clarity, JSON objects in this page are formatted with line breaks.
In reality, each event is represented as a single line.


[[object-structure]]
== Object structure

Each response consists of a sequence of events, each represented as a JSON object with the following structure:

[source,json]
----
{
    "$event": "Header | Record | Summary | Error",
    "_body": { /* event-specific payload */ }
}
----

* `$event` -- The type of event. Possible values are: `Header`, `Record`, `Summary`, `Error`.
* `_body` -- The event-specific body. The structure of this field varies depending on the event type.

Clients must consume events in the order they are received.

[NOTE]
The header `Transfer-Encoding: chunked` is used in HTTP/1.1 requests for transferring data in chunks.
HTTP/2 connections don't need this header.


[[message-sequence]]
== Message Sequencing

The Query API streaming response consists of a sequence of JSON events delivered in JSON Lines format.

Events are emitted in the following order:

1. `Header` -- Sent first. Defines the result structure and field names.
2. `Record` -- Zero or more events, each containing a single row of result data.
3. `Summary` -- Sent once, after all records are streamed. Contains execution metadata.
4. `Error` -- May appear at any point in the stream if an error occurs. When an `Error` event is emitted, no further events are sent.

The stream is complete once a `Summary` or `Error` event is received.


[[sequence-success]]
=== Successful Example

[.tabbed-example]
=====
[.include-with-sequencing]
======
[source,]
----
Header
Record
Record
Record
Summary
----
======

[.include-with-JSONL]
======
[source,json]
----
{"$event":"Header","_body":{"fields":["name","age"]}}
{"$event":"Record","_body": ["Alice",32]}
{"$event":"Record","_body": ["Bob",29]}
{"$event":"Summary","_body":{"bookmarks":["FB:kcwQ/wTfJf8rS1WY+GiIKXsCXgmQ"],"queryType": "r","resultAvailableAfter": 10,"resultConsumedAfter": 25}}
----
======
=====


[[sequence-fail]]
=== Failure Example

In case of failure, the stream is terminated immediately after the `Error` event.

[.tabbed-example]
=====
[.include-with-sequencing]
======
[source,]
----
Header
Error
----
======

[.include-with-JSONL]
======
[source,json]
----
{"$event":"Header","_body":{"fields":["name","age"]}}
{"$event":"Error","_body":[{"code":"Neo.ClientError.Statement.SyntaxError","message":"Invalid input 'RETURN'"}]}
----
======
=====


== Event Types

Each event type has a distinct payload format.


[[event-header]]
=== `Header` Event

The `Header` event is sent first in the stream.
It provides metadata about the query result, such as the names and types of the returned fields.
Information about the created transaction might also be present.

[source,json]
----
{
  "$event": "Header",
  "_body": {
    "fields": ["name", "age"]
  }
}
----

* `fields` (optional) -- An array of column names included in each subsequent `Record` event. This is not present when creating transactions without running a query.


[[event-record]]
=== `Record` Event

The `Record` event carries a single row of query data.
One `Record` event is emitted for each result row.

[.tabbed-example]
=====
[.include-with-plain-JSON]
======
[source,json]
----
{
  "$event": "Record",
  "_body": ["Antonio", 39]
}
----
======

[.include-with-typed-JSON]
======
[source,json]
----
{
  "$event": "Record",
  "_body": [{ "$type": "String", "_value": "Antonio" }, { "$type": "Integer",  "_value": "39" }]
}
----
======
=====

* `_body` -- An array containing the field values for the record. The order matches the `fields` array defined in the `Header` event. The format depends on whether xref:plain-json.adoc[] or xref:typed-json.adoc[] is used.

[IMPORTANT]
Since data arrives incrementally, the client should not assume that all `Record` events are available before processing.


[[event-summary]]
=== `Summary` Event

The `Summary` event marks the end of the stream and provides metadata about the query execution.

[source,json]
----
{
  "$event": "Summary",
  "_body": {
    "bookmarks": ["FB:kcwQ/wTfJf8rS1WY+GiIKXsCXgmQ"],
    "transaction": {
      "id": "lyU",
      "expires": "2024-10-22T15:48:29Z"
    },
    "notifications": [ /* notifications structure */ ],"counters": { /* counters structure */},
    "queryPlan": { /* query plan structure */ },
    "profiledQueryPlan": { /* profiled query plan structure */ },
    "queryType": "r",
    "resultAvailableAfter": 10,
    "resultConsumedAfter": 25
  }
}
----

* `bookmarks` (optional) -- A list of database xref:bookmarks.adoc[bookmarks]. Only present when the response represents a committed transaction.
* `transaction` (optional) -- An object with the xref:transactions.adoc[transaction] information.
* `notifications` (optional) -- Warnings or informational messages generated during query execution.  See xref:query.adoc#_server_notifications[Server notifications].
* `counters` (optional) -- Statistics about the changes performed by the query. See xref:query-counters.adoc[].
* `queryPlan` (optional) -- The logical query plan. See xref:profile-query.adoc[].
* `profiledQueryPlan` (optional) -- Detailed execution metrics, if the query was run with profiling enabled. See xref:profile-query.adoc[].
* `queryType` (optional) -- Type of query executed: read only (`"r"`), read write (`"rw"`), write only (`"w"`) and schema write (`"s"`). label:new[Introduced in 2026.07]
* `resultAvailableAfter` (optional) -- Elapsed time in milliseconds for result be available to be consumed label:new[Introduced in 2026.07]
* `resultConsumedAfter` (optional) -- Elapsed time in milliseconds to consume the result. label:new[Introduced in 2026.07]


[[event-error]]
=== `Error` Event

The `Error` event indicates that an error occurred during query execution or streaming.

[source,json]
----
{
  "$event": "Error",
  "_body": [{
    "code": "Neo.ClientError.Statement.SyntaxError"
    "message": "Invalid input 'RETURN'"
  }]
}
----

* `code` -- The Neo4j link:https://neo4j.com/docs/status-codes/current/errors/all-errors/[error code].
* `message` -- A human-readable error description.
