:page-role: new-2026.04
= Transaction Configuration

You can exert further control on transactions by providing extra optional parameters when begin transaction or run implicit transactions. You can specify:

* `maxExecutionTime`: A transaction timeout in seconds.
Transactions that run longer will be terminated by the server. The default value is set on the server side. 
* `txMetadata`: A map of metadata that gets attached to the transaction. 
These metadata get logged in the server `query.log` and are visible in the output of the `SHOW TRANSACTION` Cypher command.
Use this to tag transactions.
On typed json, the metadata fields should be typed accordantly. 

====
[discrete]
=== Example implicit transaction request

[source, headers]
----
POST http://localhost:7474/db/neo4j/query/v2
Authorization: Basic bmVvNGo6dmVyeXNlY3JldA==
Content-Type: application/json
----

[source, JSON]
----
{
  "statement": "MERGE (n:Person {name: $name, age: $age}) RETURN n AS alice",
  "parameters": {
    "name": "Alice",
    "age": 42
  },
  "txMetadata": {
    "appName": "my nice app"
  },
  "maxExecutionTime": 30
}
----

[discrete]
=== Example response

[source, headers]
----
202: Accepted 
Content-Type: application/json
----

[source, JSON, role=nocollapse]
----
{
  "data": {
    "fields": [ 
      "alice"
    ],
    "values": [  
      [
        {
          "elementId": "4:ff04df25-ff2b-4b55-98f8-6888297b025e:0",  
          "labels": [
            "Person"
          ],
          "properties": {
            "name": "Alice",
            "age": 42
          }
        }
      ]
    ]
  },
  "bookmarks": [ 
    "FB:kcwQ/wTfJf8rS1WY+GiIKXsCXgmQ"
  ]
}
----
====

====
[discrete]
=== Example begin transaction request

[source, headers]
----
POST http://localhost:7474/db/neo4j/query/v2/tx
Accept: application/json
Authorization: Basic bmVvNGo6dmVyeXNlY3JldA==
Content-Type: application/json
----

[source, JSON]
----
{
  "statement": "MERGE (n:Person {name: $name, age: $age}) RETURN n AS alice",
  "parameters": {
    "name": "Alice",
    "age": 42
  },
  "txMetadata": {
    "appName": "my nice app"
  },
  "maxExecutionTime": 30
}
----

[discrete]
=== Example response

[source, headers]
----
202: Accepted 
Content-Type: application/json
neo4j-cluster-affinity: MTAuOC41Ljc6MTc0NzQ= 
----

[source, JSON]
----
{
  "data": {
    "fields": [ 
      "alice"
    ],
    "values": [ 
      [
        {
          "elementId": "4:ff04df25-ff2b-4b55-98f8-6888297b025e:0", 
          "labels": [
            "Person"
          ],
          "properties": {
            "name": "Alice",
            "age": 42
          }
        }
      ]
    ]
  },
  "transaction": { 
    "id": "lyU",
    "expires": "2024-10-22T15:48:29Z"
  }
}
----
====